# General Settings
name: Tran Thi Thu Thuy
job_title: Former Engineering at Rakuten Mobile Inc, Japan
email: chloetran.cs@gmail,com
avatar: https://avatars.githubusercontent.com/u/87285879?v=4
#favicon: /favicon.ico
#twitter_handler: your_handler
#analytics_code: UA-XXXXXXX-2
#disqus: your_disqus_site

# Social Accounts
social_networks:
-  { name: facebook, url: 'https://www.facebook.com/ThuyTranOhmiju/' }
-  { name: google-scholar, url: 'https://scholar.google.com/citations?hl=en&user=xvgXotYAAAAJ&view_op=list_works&gmla=AP6z3OZmldriOWayFv2g_JXBxoifBWhqBEeyXPIhIPcdy_Vvx4bDCr1CFWSaRiwlMDR6BRi9LnnOPuRWkSK2MZZL' }
-  { name: linkedin, url: 'https://www.linkedin.com/in/thuy-tran-b78b231bb/' }
-  { name: github, url: 'https://github.com/ThuyTTT96' }


# Modules Settings
show_categories: 1
show_tags: 1
show_email: 1
show_rss: 1
show_comments: 1
show_menu: 1
fixed_sidebar: 1

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: "true"

# Serving
url: ""
baseurl: ""

# Includes
include: ["_pages"]

# Outputting
permalink: /:categories/:title.html
category_dir: categories

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Conversion
markdown: kramdown
excerpt_separator: <!--more-->

# Assets Settings
sass:
  sass_dir: assets/partials
  style: compressed

